Newsletter-238: translate into Chinese
bitcoinops/bitcoinops.github.io pull request #1031
Opened 2023-02-25 06:50 UTC by hulatown

2023-02-26 19:44 UTC, bitschmidty requested changes
@hulatown thanks for the translation. I noticed a couple zh links that were available to use instead of the en versions

2023-02-26 19:44 UTC, bitschmidty commented on _posts/zh/newsletters/2023-02-15-newsletter.md
> +[news234 liana]: /en/newsletters/2023/01/18/#liana-wallet-released
```suggestion
[news234 liana]: /zh/newsletters/2023/01/18/#liana
```

2023-02-26 19:44 UTC, bitschmidty commented on _posts/zh/newsletters/2023-02-15-newsletter.md
> +[news222 musig2]: /en/newsletters/2022/10/19/#musig2-security-vulnerability
```suggestion
[news222 musig2]: /zh/newsletters/2022/10/19/#musig2
```

2023-02-27 05:39 UTC, hulatown commented
> @hulatown thanks for the translation. I noticed a couple zh links that were available to use instead of the en versions

@bitschmidty Thanks Mike! Fixed. Will pay more attention next time.

2023-02-27 14:19 UTC, merged