2023-03-29-newsletter-translate-in-french
bitcoinops/bitcoinops.github.io pull request #1067
Opened 2023-03-31 16:48 UTC by Copinmalin

2023-03-31 19:23 UTC, Copinmalin commented
Thanks @bitschmidty for your confirmation

2023-04-04 13:32 UTC, bitschmidty requested changes

2023-04-04 13:32 UTC, bitschmidty commented on _posts/fr/newsletters/2023-03-29-newsletter.md
> +[news230 tp]: /en/newsletters/2022/12/14/#factory-optimized-ln-protocol-proposal
```suggestion
[news230 tp]: /fr/newsletters/2022/12/14/#proposition-d-optimisation-du-protocole-d-usines-a-canaux-ln
```

2023-04-04 13:32 UTC, bitschmidty commented on _posts/fr/newsletters/2023-03-29-newsletter.md
> +[news243 bdk]: /en/newsletters/2023/03/22/#bdk-793
```suggestion
[news243 bdk]: /fr/newsletters/2023/03/22/#bdk-793
```

2023-04-04 13:32 UTC, bitschmidty commented on _posts/fr/newsletters/2023-03-29-newsletter.md
> +[news238 libwally]: /en/newsletters/2023/02/15/#libwally-0-8-8-released
```suggestion
[news238 libwally]: /fr/newsletters/2023/02/15/#sortie-de-libwally-0-8-8
```

2023-04-04 13:32 UTC, bitschmidty commented on _posts/fr/newsletters/2023-03-29-newsletter.md
> +[news239 codex32]: /en/newsletters/2023/02/22/#proposed-bip-for-codex32-seed-encoding-scheme
```suggestion
[news239 codex32]: /fr/newsletters/2023/02/22/#proposition-de-bip-pour-le-systeme-d-encodage-des-semences-codex32
```

2023-04-04 13:52 UTC, bitschmidty approved these changes
ACK, thank you @Copinmalin !

2023-04-04 13:53 UTC, merged