Newsletter-246-translate-in-French
bitcoinops/bitcoinops.github.io pull request #1085
Opened 2023-04-14 16:52 UTC by Copinmalin

2023-04-17 13:37 UTC, bitschmidty requested changes

2023-04-17 13:37 UTC, bitschmidty commented on _posts/fr/newsletters/2023-04-12-newsletter.md
> +[news243 bdk]: /en/newsletters/2023/03/22/#bdk-793
```suggestion
[news243 bdk]: /fr/newsletters/2023/03/22/#bdk-793
```

2023-04-18 20:05 UTC, Copinmalin commented
@bitschmidty , hello done, thanks for your linx eyes

2023-04-19 16:36 UTC, bitschmidty approved these changes
ACK, thank you @Copinmalin !

2023-04-19 16:36 UTC, merged