Newsletter-252: translate into Chinese
bitcoinops/bitcoinops.github.io pull request #1145
Opened 2023-06-08 13:53 UTC by hulatown

2023-06-12 13:34 UTC, bitschmidty requested changes

2023-06-12 13:34 UTC, bitschmidty commented on _includes/specials/policy/zh/02-cache-utility.md
> +[policy01]: /en/newsletters/2023/05/17/#waiting-for-confirmation-1-why-do-we-have-a-mempool
```suggestion
[policy01]: /zh/newsletters/2023/05/17/#等待确认-1-我们为什么需要一个交易池
```

2023-06-12 13:54 UTC, bitschmidty approved these changes
ACK, thank you @hulatown !

2023-06-12 14:22 UTC, bitschmidty commented
@hulatown there were conflicts with this branch so I rebased and squashed but didn’t have permission to push the changes to this branch so I opened a separate branch and PR. Can you take a look? https://github.com/bitcoinops/bitcoinops.github.io/pull/1149

2023-06-13 02:11 UTC, hulatown commented
> 

Thanks Mike! It looks good to me

2023-06-13 12:44 UTC, bitschmidty commented
Closed in favor of rebased https://github.com/bitcoinops/bitcoinops.github.io/pull/1149

2023-06-13 12:44 UTC, closed without merging