Newsletter-254-Translate-into-French
bitcoinops/bitcoinops.github.io pull request #1154
Opened 2023-06-14 20:04 UTC by Copinmalin

2023-06-21 13:26 UTC, bitschmidty requested changes

2023-06-21 13:26 UTC, bitschmidty commented on _posts/fr/2023-05-17-policy.md
> +{% include specials/policy/fr/03-encheres-pour-lachat-dun-bloc-despace.md %}
```suggestion
{% include specials/policy/fr/03-encheres-pour-l-achat-d-un-bloc-d-espace.md %}
```

2023-06-21 14:58 UTC, Copinmalin commented
@bitschmidty : change seem not resolve problem :.-(

2023-06-24 22:20 UTC, Copinmalin commented
@bitschmidty : hello, I need your help please

I don't understand why link for news 252 and 253 was good before add link for news 254 and are now in error

2023-06-26 15:58 UTC, bitschmidty approved these changes
Tested links, ACK

@Copinmalin let me know if you are ok with the changes I made.

2023-06-26 17:20 UTC, Copinmalin commented
Thanks for your help @bitschmidty ,

I don't understand because two times I had no error in policy.md 
![Capture d'écran 2023-06-26 191459](https://github.com/bitcoinops/bitcoinops.github.io/assets/4174888/a20e1f1a-ea7d-46e5-a196-eaefbbc514d0)
![Capture d'écran 2023-06-26 191448](https://github.com/bitcoinops/bitcoinops.github.io/assets/4174888/92e02908-624f-40e1-9e29-e96acbc77420)

And after insert link for news 254, some error with previous link.
I'm so confused :-(

Many thanks for your patience with me

2023-06-27 16:42 UTC, merged

2023-07-03 10:05 UTC, Copinmalin commented
@bitschmidty : we have a problem on this newsletter with a wrong link to policy : 
actually point to english version,

Need to be : 
{% include specials/policy/fr/04-estimation-taux-de-frais.md %}

new PR or can we change this one ?

2023-07-04 13:08 UTC, bitschmidty commented
@Copinmalin can you open a new PR for the correction?