Newsletter-260:Translate into Japanese
bitcoinops/bitcoinops.github.io pull request #1207
Opened 2023-07-19 12:26 UTC by azuchi

2023-07-19 15:51 UTC, bitschmidty requested changes

2023-07-19 15:51 UTC, bitschmidty commented on _includes/specials/policy/ja/10-get-involved.md
Can you add this entry into the Series page? https://deploy-preview-1207--bitcoinops.netlify.app/ja/blog/waiting-for-confirmation/

2023-07-19 23:54 UTC, azuchi commented on _includes/specials/policy/ja/10-get-involved.md
@bitschmidty oh, thanks. I added.

2023-07-20 12:58 UTC, bitschmidty approved these changes
ACK, thanks @azuchi !

2023-07-20 12:58 UTC, merged