Newsletter 261 translate in french
bitcoinops/bitcoinops.github.io pull request #1229
Opened 2023-08-06 15:50 UTC by Copinmalin

2023-08-09 18:09 UTC, bitschmidty requested changes

2023-08-09 18:09 UTC, bitschmidty commented on _posts/fr/newsletters/2023-07-26-newsletter.md
> +Une autre considération discutée était de savoir si une UTXO d'une valeur de _n_ devrait être autorisée à annoncer un canal
@Copinmalin the markdown formatting for this bullet and the ones that follow is off. Can you correct to match the formatting for the above few bullets?

2023-08-09 18:09 UTC, bitschmidty commented on _posts/fr/newsletters/2023-07-26-newsletter.md
> +  - [Pourquoi y a-t-il 17 versions natives segwit ?]({{bse}}118974)
```suggestion
- [Pourquoi y a-t-il 17 versions natives segwit ?]({{bse}}118974)
```

2023-08-11 08:44 UTC, bitschmidty reviewed
@Copinmalin the 

PTLCs et surpaiement redondant
Propositions d'atténuation des attaques de saturation des canaux
Engagements simplifiés
Le processus de spécification

bullets are still mis-formatted, can you correct?

2023-08-12 12:57 UTC, murchandamus reviewed
Looks like everything is indented correctly now

2023-08-13 09:17 UTC, murchandamus commented
I checked the links, looked over it visually. The issue raised by @bitschmidty seems to be resolved. 
Altogether, I think this is good to go, so I’ll merge.

2023-08-13 09:19 UTC, merged