Newsletter 263 translate in french
bitcoinops/bitcoinops.github.io pull request #1236
Opened 2023-08-09 20:59 UTC by Copinmalin

2023-08-14 16:48 UTC, bitschmidty requested changes

2023-08-14 16:48 UTC, bitschmidty commented on _posts/fr/newsletters/2023-08-09-newsletter.md
> +[news261 jamming]: /en/newsletters/2023/07/26/#channel-jamming-mitigation-proposals
I think:

```suggestion
[news261 jamming]: /fr/newsletters/2023/07/26/#propositions-d-attenuation-des-attaques-de-saturation-des-canaux
```

2023-08-16 15:32 UTC, bitschmidty commented on _posts/fr/newsletters/2023-08-09-newsletter.md
> +[news261 jamming]: /en/newsletters/2023/07/26/#channel-jamming-mitigation-proposals
@Copinmalin I applied this suggestion to the code. Let me know if you think this PR is good to go

2023-08-16 18:11 UTC, murchandamus approved these changes
LGTM, but I’m not @Copinmalin ;)

2023-08-17 10:52 UTC, Copinmalin commented
you are my guides, if you agree i agree 😅

2023-08-17 16:30 UTC, merged

2023-08-17 16:30 UTC, murchandamus commented
Okay, shipped it. :)