Newsletter-268: Translate in French
bitcoinops/bitcoinops.github.io pull request #1305
Opened 2023-09-14 16:39 UTC by Copinmalin

2023-09-21 09:43 UTC, bitschmidty requested changes

2023-09-21 09:43 UTC, bitschmidty commented on _topics/fr/client-side-validation.md
@Copinmalin Thanks for translating the topic pages!

Unfortunately, the site doesnt support translations in the topic section (yet). Can you drop these from this commit and save for a future PR once we can support that?

2023-09-21 20:21 UTC, Copinmalin commented on _topics/fr/client-side-validation.md
Done !

2023-09-25 13:22 UTC, bitschmidty approved these changes
ACK, thank you @Copinmalin !

2023-09-25 13:22 UTC, merged