Newsletter-269:Translate into Japanese
bitcoinops/bitcoinops.github.io pull request #1311
Opened 2023-09-20 11:02 UTC by azuchi

2023-09-21 09:39 UTC, bitschmidty requested changes

2023-09-21 09:39 UTC, bitschmidty commented on _posts/ja/newsletters/2023-09-20-newsletter.md
> +- **Bitcoinに似たScript Symbolic Trace (B'SST)のリリース:**
```suggestion
- **Bitcoinに似たScript Symbolic Tracer (B'SST)のリリース:**
```

2023-09-21 09:39 UTC, bitschmidty commented on _posts/ja/newsletters/2023-09-20-newsletter.md
> +  [B'SST][]は、BitcoinとElementのスクリプト分析ツールで、「スクリプトが強制する条件、
```suggestion
  [B'SST][]は、BitcoinとElementsのスクリプト分析ツールで、「スクリプトが強制する条件、
```

2023-09-21 12:21 UTC, azuchi commented on _posts/ja/newsletters/2023-09-20-newsletter.md
> +  [B'SST][]は、BitcoinとElementのスクリプト分析ツールで、「スクリプトが強制する条件、
@bitschmidty I fixed.

2023-09-25 13:20 UTC, bitschmidty approved these changes
ACK, thank you @azuchi and sorry for the delay in reviewing!

2023-09-25 13:20 UTC, merged