Newsletter-2: translate into Chinese
bitcoinops/bitcoinops.github.io pull request #1531
Opened 2024-02-28 02:48 UTC by bittomhan

2024-03-01 15:03 UTC, bitschmidty commented
@hulatown do you have time to provide a quick review here?

2024-03-01 15:34 UTC, hulatown commented
> @hulatown do you have time to provide a quick review here?

Sure! Reviewed with only 2 suggestions

2024-03-01 19:34 UTC, bitschmidty commented
> > @hulatown do you have time to provide a quick review here?
> 
> Sure! Reviewed with only 2 suggestions

I dont see the suggestions here?

2024-03-02 01:02 UTC, hulatown commented
> > > @hulatown do you have time to provide a quick review here?
> > 
> > 
> > Sure! Reviewed with only 2 suggestions
> 
> I dont see the suggestions here?

Sorry, forgot to submit last night... Now it should work?

2024-03-02 13:10 UTC, bittomhan commented on _posts/zh/newsletters/2018-07-03-newsletter.md
> +[newsletter #1]: /en/newsletters/2018/06/26/
感谢胡老师修正！

2024-03-02 13:10 UTC, bittomhan commented on _posts/zh/newsletters/2018-07-03-newsletter.md
> +[newsletter page]: /en/newsletters/
非常感谢胡老师修正！

2024-03-02 13:12 UTC, bittomhan commented
> > > > @hulatown do you have time to provide a quick review here?
> > > 
> > > 
> > > Sure! Reviewed with only 2 suggestions
> > 
> > 
> > I dont see the suggestions here?
> 
> Sorry, forgot to submit last night... Now it should work?

I greatly appreciate Jeffery Hu's corrections. I've noticed that in my references, I retained the English link content instead of replacing it with the Chinese equivalent, which is something I'll be more mindful of in the future. Thank you very much!

2024-03-04 14:40 UTC, bitschmidty requested changes
@bittomhan The suggestions are resolved, but I still see the /en/ links in the file, can you take another look?

2024-03-04 23:19 UTC, bittomhan commented
I was not previously familiar with this procedure and thought that simply clicking "resolved" would suffice for agreement. After clarification, I understand that it's necessary to click "commit to batches." Both items have now been confirmed and modified accordingly.

The tests have now been fully passed, and I'm very grateful for Jeffery Hu's patient review, as well as your thorough inspection.

2024-03-06 13:48 UTC, bitschmidty approved these changes
ACK, thank you @bittomhan and @hulatown !

2024-03-06 13:49 UTC, merged

2024-03-06 13:49 UTC, bitschmidty commented
Squashed commits and merged! 🚀