Newsletter-3: translate into Chinese
bitcoinops/bitcoinops.github.io pull request #1545
Opened 2024-03-07 08:44 UTC by bittomhan

2024-03-09 14:30 UTC, bitschmidty reviewed
Links and formatting looked ok to me. Ill give @hulatown some time to take a look as well

2024-03-11 05:23 UTC, hulatown commented
> Links and formatting looked ok to me. Ill give @hulatown some time to take a look as well

Sure! Will take a look!

2024-03-11 05:34 UTC, hulatown requested changes
Changes suggested

2024-03-11 05:34 UTC, hulatown commented on _posts/zh/newsletters/2018-07-10-newsletter.md
> +本周的 Newsletter 包括有关最低费用和即将发布的比特币核心版本的新闻和行动项目，关于 Schnorr 签名提案的特别专题，以及最近在里斯本举行的 Building on Bitcoin 会议记录。
```suggestion
本周的 Newsletter 包括有关最低费用和即将发布的 Bitcoin Core 版本的新闻和行动项目，关于 Schnorr 签名提案的特别专题，以及最近在里斯本举行的 Building on Bitcoin 会议记录。
```

2024-03-11 05:34 UTC, hulatown commented on _posts/zh/newsletters/2018-07-10-newsletter.md
> +    请注意，要在 Bitcoin Core 中将最低中继费用降低到其默认值以下，您需要更改两个设置。下面显示的是 Bitcoin Core 0.16.1 中具有默认值的两个设置；要降低这些值，请将它们都更改为相同的值，但请注意，将它们降低太多（可能低于默认值的 1/10）会使您面临浪费带宽的攻击，并降低您的节点的 BIP152 紧凑块效率。
```suggestion
    请注意，要在 Bitcoin Core 中将最低中继费用降低到其默认值以下，您需要更改两个设置。下面显示的是 Bitcoin Core 0.16.1 中具有默认值的两个设置；要降低这些值，请将它们都更改为相同的值，但请注意，将它们降低太多（可能低于默认值的 1/10）会使您面临浪费带宽的攻击，并降低您的节点的 BIP152 致密区块效率。
```

2024-03-11 22:37 UTC, bittomhan commented on _posts/zh/newsletters/2018-07-10-newsletter.md
> +本周的 Newsletter 包括有关最低费用和即将发布的比特币核心版本的新闻和行动项目，关于 Schnorr 签名提案的特别专题，以及最近在里斯本举行的 Building on Bitcoin 会议记录。
非常感谢您，我之前的没有翻译，这里确实是没有注意到

2024-03-11 22:39 UTC, bittomhan commented on _posts/zh/newsletters/2018-07-10-newsletter.md
> +    请注意，要在 Bitcoin Core 中将最低中继费用降低到其默认值以下，您需要更改两个设置。下面显示的是 Bitcoin Core 0.16.1 中具有默认值的两个设置；要降低这些值，请将它们都更改为相同的值，但请注意，将它们降低太多（可能低于默认值的 1/10）会使您面临浪费带宽的攻击，并降低您的节点的 BIP152 紧凑块效率。
非常感谢！专业名词我得有个参考，我向您私信咨询

2024-03-11 22:39 UTC, bittomhan commented
I'm very grateful for Jeffery Hu's review. There were indeed some aspects I overlooked, and I will make sure to pay closer attention and conduct thorough checks in the future!

2024-03-13 15:47 UTC, bitschmidty approved these changes
ACK, thank you @bittomhan and @hulatown !

2024-03-13 15:48 UTC, merged