Newsletter-57: translate into Chinese
bitcoinops/bitcoinops.github.io pull request #1856
Opened 2024-08-29 14:39 UTC by bittomhan

2024-08-29 14:43 UTC, bittomhan commented
translate "Lightning BOLTs" to "闪电网络规范"
modified all "Bitcoin Improvement Proposals(BIPs)" to "比特币改进提案（BIPs）" and removed those space on both sides

2024-09-03 10:23 UTC, bitschmidty requested changes

2024-09-03 10:23 UTC, bitschmidty commented on _posts/zh/newsletters/2019-07-31-newsletter.md
> +  -**<!--dns-seeds-can-return-only-nodes-signaling-bip111-->** *DNS seeds 只能返回信号 BIP111 的节点：*大多数 P2P 轻钱包会查询一个或多个比特币 DNS seeds 以获取要使用的节点列表。一些 seeds 允许根据节点配置的服务比特来筛选返回的节点[^dns-query]，其中支持布隆过滤器的服务位由 [BI
```suggestion
  - **<!--dns-seeds-can-return-only-nodes-signaling-bip111-->** *DNS seeds 只能返回信号 BIP111 的节点：*大多数 P2P 轻钱包会查询一个或多个比特币 DNS seeds 以获取要使用的节点列表。一些 seeds 允许根据节点配置的服务比特来筛选返回的节点[^dns-query]，其中支持布隆过滤器的服务位由 [BIP111][] 指定。
```

2024-09-03 10:23 UTC, bitschmidty commented on _posts/zh/newsletters/2019-07-31-newsletter.md
> +  -**<!--bip157-would-use-more-bandwidth-than-bip37-->***BIP157 将使用比 BIP37 更多的带宽：*有人建议，一些使用 [BIP37][]布隆过滤器的用户将无法切换到 [BIP157][] 致密区块过滤器，因为后者的带宽使用更高。Optech 在 [Newsletter #43][] 中简要调查了过滤器大小，发现过滤器本身每月使用不
```suggestion
  - **<!--bip157-would-use-more-bandwidth-than-bip37-->***BIP157 将使用比 BIP37 更多的带宽：*有人建议，一些使用 [BIP37][]布隆过滤器的用户将无法切换到 [BIP157][] 致密区块过滤器，因为后者的带宽使用更高。Optech 在 [Newsletter #43][] 中简要调查了过滤器大小，发现过滤器本身每月使用不到 100 MB。客户端还需要下载匹配的区块，这将根据其活动而有所不同（对于典型用户来说，大约每个发送或接收的交易对应一个区块；大多数区块小于 2 MB）。目前尚不清楚有多少用户会因必须下载这些数据量而受到显著影响。
```

2024-09-03 10:23 UTC, bitschmidty commented on _posts/zh/newsletters/2019-07-31-newsletter.md
> +[bitnodes dashboard]: https://bitnodes.earn.com/dashboard/
Probably update to

```suggestion
[bitnodes dashboard]: https://bitnodes.io/
```

2024-09-04 13:03 UTC, merged