Newsletter 316 translate in French
bitcoinops/bitcoinops.github.io pull request #1862
Opened 2024-09-01 09:36 UTC by Copinmalin

2024-09-01 22:07 UTC, GaloisField2718 reviewed
Merci copin pour tes traductions ! 

J'ai noté quelques trucs qui me semblent bizarre et quelques typos. Certaine sont importantes d'autres sont de simples remarques générales comme la traduction de vidange d'élagage pour pruning flushes qui fait bizarre mais qui semble pas faux.

2024-09-04 01:09 UTC, GaloisField2718 requested changes
Request Changes

2024-09-04 09:58 UTC, GaloisField2718 approved these changes
Approve request changes

2024-09-05 08:22 UTC, Copinmalin commented on _posts/fr/newsletters/2024-08-16-newsletter.md
> +  doivent régler le temps des blocs de recalibrage à 8 semaines plus dans le futur que le bloc au
j'ai proposé "8 semaines de plus que" ^^

2024-09-05 08:24 UTC, Copinmalin commented on _posts/fr/newsletters/2024-08-16-newsletter.md
> +  courtes économiquement avantageuses mais les routes longues coûteuses.
synthétisé en : "rendant les routes courtes moins couteuses en calcul que les routes longues"

2024-09-05 08:24 UTC, Copinmalin commented on _posts/fr/newsletters/2024-08-16-newsletter.md
> +  [posté][teinturier auth] sur Delving Bitcoin pour proposer des méthodes permettant aux dépensiers
@Jluc-bitcoinfr me corrige aussi avec ce mot ^^

2024-09-05 08:26 UTC, Copinmalin commented on _posts/fr/newsletters/2024-08-16-newsletter.md
> +  défaut pour cacher les identités du dépensier et du récepteur, donc des mécanismes supplémentaires
payeur plutôt qu'envoyeur alors ? ^^

2024-09-05 08:29 UTC, Copinmalin commented on _posts/fr/newsletters/2024-08-16-newsletter.md
> +  Teinturier commence par décrire un mécanisme de distribution de _clé de contact_ opt-in que Bob peut
je ne pense que l'on puisse modifier la mise en forme du bulletin par rapport à l'original.

plutôt : 
"un mécanisme de distribution d'une souscription de _clé de contact_ "

2024-09-05 08:29 UTC, Copinmalin commented on _posts/fr/newsletters/2024-08-16-newsletter.md
> +  définis par le dépensier (tels que le champ `payer_note` en forme libre) peuvent être marqués comme
ou payeur ?

2024-09-05 08:35 UTC, Copinmalin commented on _posts/fr/newsletters/2024-08-16-newsletter.md
> +  portefeuilles et d'autres applications activées par Bitcoin. Le paquet Rust `bdk` original a été
en laissant "crates" je trouvais que c'était pas vraiment beau comme mot, et si c'est pour mettre un autre anglicisme.

package c'est paquet finalement.

2024-09-05 08:59 UTC, GaloisField2718 commented on _posts/fr/newsletters/2024-08-16-newsletter.md
> +  courtes économiquement avantageuses mais les routes longues coûteuses.
Parfait !

2024-09-05 09:01 UTC, GaloisField2718 commented on _posts/fr/newsletters/2024-08-16-newsletter.md
> +  défaut pour cacher les identités du dépensier et du récepteur, donc des mécanismes supplémentaires
J'hésite... envoyeur pour les communications c'est plus d'usage payeur pour les paiements c'est plus usuels. 
Comme c'est un réseau de communication de paiements... 😅

2024-09-05 09:03 UTC, GaloisField2718 commented on _posts/fr/newsletters/2024-08-16-newsletter.md
> +  Teinturier commence par décrire un mécanisme de distribution de _clé de contact_ opt-in que Bob peut
Ah ok je savais pas pour la forme du bulletin. 
Du coup oui ça semble correct et suffisant.

2024-09-05 09:06 UTC, GaloisField2718 commented on _posts/fr/newsletters/2024-08-16-newsletter.md
> +  portefeuilles et d'autres applications activées par Bitcoin. Le paquet Rust `bdk` original a été
C'est pas faux. 
Apparemment bibliothèque peut être plus adapté pour Rust [Rust Book fr](https://jimskapt.github.io/rust-book-fr/ch07-01-packages-and-crates.html).

2024-09-06 13:24 UTC, bitschmidty approved these changes
ACK, thank you @Copinmalin and @GaloisField2718

2024-09-06 13:24 UTC, merged