Newsletter 317 translate in French
bitcoinops/bitcoinops.github.io pull request #1863
Opened 2024-09-01 10:14 UTC by Copinmalin

2024-09-04 00:54 UTC, GaloisField2718 requested changes
Change request

2024-09-04 00:54 UTC, GaloisField2718 commented on _posts/fr/newsletters/2024-08-23-newsletter.md
> +  Sign-to-contract est une variation de [pay-to-contract][topic p2c] : dans pay-to-contract, la clé
publique du destinataire est modifiée ; dans sign-to-contract, le nonce de signature de l'envoyeur

2024-09-04 01:00 UTC, GaloisField2718 requested changes
Les changements sont à copier coller. 
Dois-je faire un fork et le proposer sur ta branche copinmalin ?

2024-09-05 08:43 UTC, Copinmalin commented on _posts/fr/newsletters/2024-08-23-newsletter.md
> +  publique du destinataire est modifiée ; dans sign-to-contract, le nonce de signature du dépenseur
envoyeur ou payeur finalement ?

2024-09-05 09:07 UTC, GaloisField2718 commented on _posts/fr/newsletters/2024-08-23-newsletter.md
> +  publique du destinataire est modifiée ; dans sign-to-contract, le nonce de signature du dépenseur
Payeur ?!

2024-09-05 09:09 UTC, GaloisField2718 commented on _posts/fr/newsletters/2024-08-23-newsletter.md
> +  publique du destinataire est modifiée ; dans sign-to-contract, le nonce de signature du dépenseur
Au vue de la dernière remarque à ce sujet pour parler paiement plutôt payeur. 
Je sais pas ce que d'autres en pensent.

2024-09-07 10:36 UTC, bitschmidty commented on _posts/fr/newsletters/2024-08-23-newsletter.md
> +[news315 blinded]: /en/newsletters/2024/08/09/#lnd-8735
Once we get changes to fr315 merged we can update this link, the rest looks good

2024-09-16 16:00 UTC, bitschmidty approved these changes
ACK, thank you @Copinmalin

2024-09-16 16:00 UTC, merged