Newsletter-70: translate into Chinese
bitcoinops/bitcoinops.github.io pull request #1899
Opened 2024-09-17 13:51 UTC by bittomhan

2024-09-17 14:51 UTC, bittomhan commented
I really do not know what happend so that the `make production` can not link to the page.

<img width="987" alt="Screenshot 2024-09-17 at 10 46 54 PM" src="https://github.com/user-attachments/assets/668fad75-7bbd-4fea-b3da-89730eb4c325">

May be the `en` and `es` version is OK.

<img width="985" alt="Screenshot 2024-09-17 at 10 46 45 PM" src="https://github.com/user-attachments/assets/03da2080-240c-457f-9bb4-f2c352a00a9c">

So should I just pull request the linking page `Bitcoin Optech Schnorr Taproot Workshop` first? Or what should I do to fix this?

2024-09-19 16:14 UTC, bitschmidty reviewed
We screwed up on the URL/permalink here in the original and other translations

schorr vs schnorr

So these suggestions should be the correct ones. But first we need to correct other versions. Ill open a PR now

2024-09-19 16:14 UTC, bitschmidty commented on _posts/zh/2019-10-29-schnorr-taproot-workshop.md
> +name: 2019-10-29-schorr-taproot-workshop-zh
```suggestion
name: 2019-10-29-schnorr-taproot-workshop-zh
```

2024-09-19 16:14 UTC, bitschmidty commented on _posts/zh/2019-10-29-schnorr-taproot-workshop.md
> +slug: 2019-10-21-schorr-taproot-workshop-zh
```suggestion
slug: 2019-10-21-schnorr-taproot-workshop-zh
```

2024-09-19 16:14 UTC, bitschmidty commented on _posts/zh/2019-10-29-schnorr-taproot-workshop.md
> +permalink: /zh/schorr-taproot-workshop/
```suggestion
permalink: /zh/schnorr-taproot-workshop/
```

2024-09-20 11:50 UTC, bitschmidty requested changes

2024-09-20 11:50 UTC, bitschmidty commented on _posts/zh/newsletters/2019-10-30-newsletter.md
> +[taproot workshop]: /zh/schorr-taproot-workshop/
```suggestion
[taproot workshop]: /zh/schnorr-taproot-workshop/
```

2024-09-20 12:42 UTC, bittomhan commented
@bitschmidty Thank you for your efforts and I learned what is hugo conversion.
But it seemed still did not slove the problem yet?

2024-09-21 10:46 UTC, bitschmidty reviewed
Took a bit of playing around but I think this is the issue

2024-09-21 10:46 UTC, bitschmidty commented on _posts/zh/2019-10-29-schnorr-taproot-workshop.md
> +------
```suggestion
---
```

2024-09-21 13:25 UTC, bittomhan commented
@bitschmidty 
It seemed like something almost there since it shows the link to `en` version has promblem on the `zh` file.
<img width="815" alt="Screenshot 2024-09-21 at 9 23 38 PM" src="https://github.com/user-attachments/assets/0afc905d-fc63-4666-9bf2-13c262cea862">

2024-09-21 15:36 UTC, bitschmidty commented
@bittomhan can you rebase on master which has the changes from https://github.com/bitcoinops/bitcoinops.github.io/pull/1902 regarding these pages?

2024-09-21 22:40 UTC, bittomhan commented
> @bittomhan can you rebase on master which has the changes from #1902 regarding these pages?

It works! Thank you very much!

2024-09-23 10:34 UTC, merged