Newsletter-86: translate into Chinese
bitcoinops/bitcoinops.github.io pull request #1940
Opened 2024-10-07 22:46 UTC by bittomhan

2024-10-16 12:44 UTC, bitschmidty requested changes

2024-10-16 12:44 UTC, bitschmidty commented on _posts/zh/newsletters/2020-02-26-newsletter.md
> +[news46 sbc]: /en/newsletters/2019/02/05/#notable-talks-from-the-stanford-blockchain-conference
```suggestion
[news46 sbc]: /zh/newsletters/2019/02/05/#斯坦福区块链会议上的值得注意的演讲
```

2024-10-16 12:49 UTC, bittomhan commented
@bitschmidty Sometimes it is a bit messy for me to conform all formats through git.
I will check the later merge.
Thank you!

2024-10-19 10:44 UTC, bitschmidty approved these changes
ACK, thank you @hulatown

2024-10-19 10:44 UTC, merged