Newsletter-101: translate into Chinese
bitcoinops/bitcoinops.github.io pull request #1982
Opened 2024-10-29 11:18 UTC by bittomhan

2024-10-29 13:05 UTC, bittomhan commented
@bitschmidty  I do not know what happened in the docker and remote github auto check:

![Screenshot 2024-10-29 at 9 02 26 PM](https://github.com/user-attachments/assets/fa1c62fb-ec05-4dfc-afb3-718a304e35b4)
![Screenshot 2024-10-29 at 9 03 14 PM](https://github.com/user-attachments/assets/36ec5a57-8728-4cfb-be27-22bd302f0dd3)

2024-10-30 10:30 UTC, bitschmidty requested changes

2024-10-30 10:30 UTC, bitschmidty commented on _posts/zh/newsletters/2020-06-10-newsletter.md
> +[news67 static_remotekey]: /en/newsletters/2019/10/09/#bolts-642
```suggestion
[news67 static_remotekey]: /zh/newsletters/2019/10/09/#bolts-642
```

2024-10-30 10:39 UTC, bitschmidty approved these changes
ACK

2024-10-30 10:43 UTC, merged