Newsletter-110: translate into Chinese
bitcoinops/bitcoinops.github.io pull request #1994
Opened 2024-10-30 01:02 UTC by bittomhan

2024-11-12 14:47 UTC, bitschmidty requested changes
@bittomhan would you mind rebasing on master to resolve the conflicts with zh109

2024-11-13 00:32 UTC, bittomhan commented
> @bittomhan would you mind rebasing on master to resolve the conflicts with zh109

I have update all links under `newsletter/zh/` path. 
Thank you for your check. This is also a chance for me to pratice `git`.

2024-11-25 17:28 UTC, bitschmidty requested changes

2024-11-25 17:28 UTC, bitschmidty commented on _posts/zh/newsletters/2020-08-12-newsletter.md
> +[news108 wtxid]: /en/newsletters/2020/07/29/#bitcoin-core-18044
```suggestion
[news108 wtxid]: /zh/newsletters/2020/07/29/#bitcoin-core-18044
```

2024-11-25 17:28 UTC, bitschmidty commented on _posts/zh/newsletters/2020-08-12-newsletter.md
> +[news69 signcheck rpc]: /en/newsletters/2019/10/23/#c-lightning-3150
```suggestion
[news69 signcheck rpc]: /zh/newsletters/2019/10/23/#c-lightning-3150
```

2024-11-25 17:28 UTC, bitschmidty commented on _posts/zh/newsletters/2020-08-12-newsletter.md
> +[news95 ln atomicity]: /en/newsletters/2020/04/29/#new-attack-against-ln-payment-atomicity
```suggestion
[news95 ln atomicity]: /zh/newsletters/2020/04/29/#new-attack-against-ln-payment-atomicity
```

2024-11-25 18:08 UTC, bitschmidty approved these changes

2024-11-25 18:09 UTC, merged