Topics: update with mentions from August 2020
bitcoinops/bitcoinops.github.io pull request #460
Opened 2020-09-21 13:01 UTC by harding

&nbsp;

2020-09-22 14:37 UTC, bitschmidty requested changes
Tested links. 

Just one text item caught.

2020-09-22 14:37 UTC, bitschmidty commented on _topics/en/psbt.md
> +  - title: BIP176 specification of PSBT updated in response to fee overpayment attack
s/BIP176/BIP174

2020-09-23 10:17 UTC, jnewbery reviewed
One minor typo inline.

I've always found that reviewing these PRs involves more overhead than I'd like (opening a diff, opening a browser, figuring out which topic page to open, scanning through that page for new links). This time, I used the following method, which seemed more efficient:

- Open a terminal and browser side by side
- Run `git diff HEAD~ | sed "s'url: /'url: https://bitcoinops.org/'" | colordiff | less -r` in the terminal (converts internal links to absolute links and recolorizes the output).
- Click on the new links in the less output to open the link in the browser.

@bitschmidty - I don't know what you're doing to review these, but perhaps the method above will save you a bit of time too?

@harding - I don't know how you're collecting these. I wonder if adding tags to the newsletter files would make them easier to collect/verify that you haven't missed any?

2020-09-23 10:17 UTC, jnewbery commented on _topics/en/schnorr-signatures.md
> +  - title: Proposal to update BIP340 schnorr signatures to use eveness tiebreaker
s/eveness/evenness/

2020-09-23 10:53 UTC, harding commented
@jnewbery 

> @harding I don't know how you're collecting these. I wonder if adding tags to the newsletter files would make them easier to collect/verify that you haven't missed any?

I collect them by just skimming the newsletters from the previous month and editing the topic files as appropriate.  We already have a partial tagging system in place: when the newsletter mentions a topic, it usually links to the corresponding topic page, so the blue links are an obvious signal.  I don't currently do any verification.

A test we could add (perhaps independent from CI) is a backlink check: everytime the newsletter (or maybe other pages) links to a topic page, that topic page has to link back to the newsletter/page.  This would be fallible when we discuss a topic more than once in a single newsletter, and it would need the ability to override backlinks sometimes (e.g. when a topic is only mentioned incidentally in a news item), but I think such a test would be possible.

Either with or without that test, something to consider would be moving to more frequent topic updates.  We currently do monthly updates (when I remember!) but we could also bundle the updates with newsletters.  If we made the updates in the same PR as added the newsletter, then reviewers would be more likely to notice when we'd forgotten to update the topic listing for content in that newsletter; a downside would possibly be a bit more churn on the newsletter diff.  Alternatively, if we made the updates for newsletter n the following week in newsletter n+1, churn would be minimal and reviewers might still have a good enough recollection of the previous week's content to warn about missing links.  The advantages to both approaches would be fewer changes per update to review and the topic index would remain always up-to-date.

I slightly prefer combining topic updates with the newsletter PRs in order to keep everything up to date, but I don't want to place too much burden on reviewers, so please say something if that sounds annoying.

2020-09-23 12:07 UTC, jnewbery commented
> A test we could add ... This would be fallible

Sounds to me like too much machinery/overhead to be worth it. @harding - if you think it'd be helpful for you and want to implement it, I'm happy to review, but it doesn't sound worth it to me.

> something to consider would be moving to more frequent topic updates

ACK from me. Sounds like this would be more efficient for you, and I review both the newsletters and topics updates anyway, so it's a win for me. Newsletter reviewers who don't want to review the new topics links shouldn't feel obligated to - they can just review the newsletter as normal.

2020-09-23 12:07 UTC, merged

2020-09-23 15:18 UTC, bitschmidty commented
> I don't know what you're doing to review these

I currently build locally and then review text and check new links in browser for each file/topic changed.

> I slightly prefer combining topic updates with the newsletter PRs in order to keep everything up to date

Im happy to help with this review (and adding links when authoring) each week.

2020-09-23 16:37 UTC, harding commented
@jnewbery @bitschmidty re: you both being good with topic updates in newsletters: awesome, thanks!  Next Wednesday after Mike merges `#117`, I'll open a topic update for September; then I'll include per-newsletter topic updates starting with `#118`.