Newsletter-154:Translate into Japanese
bitcoinops/bitcoinops.github.io pull request #594
Opened 2021-06-24 01:36 UTC by azuchi

2021-06-24 15:16 UTC, bitschmidty requested changes
@azuchi looks good with one suggestion

2021-06-24 15:16 UTC, bitschmidty commented on _posts/ja/newsletters/2021-06-23-newsletter.md
> +[additive payment batching]: /en/cardcoins-rbf-batching/
You can link to the /ja/ version now :)

2021-06-25 00:04 UTC, azuchi commented on _posts/ja/newsletters/2021-06-23-newsletter.md
> +[additive payment batching]: /en/cardcoins-rbf-batching/
@bitschmidty thanks! I fixed it.

2021-06-25 16:34 UTC, bitschmidty approved these changes
@azuchi thanks for the translation again!

2021-06-25 16:34 UTC, merged