Newsletters: add 205 (2022-06-22)
bitcoinops/bitcoinops.github.io pull request #789
Opened 2022-06-18 10:13 UTC by harding

- [ ] Clients/services section @bitschmidty 
- [ ] Releases/RCs and topics @harding

2022-06-21 09:37 UTC, johnzweng requested changes

2022-06-21 09:37 UTC, johnzweng commented on _posts/en/newsletters/2022-06-22-newsletter.md
> +[poelstra timestamping]: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-June/020569.htmla
Small typo in file suffix: *.html**a**
```suggestion
[poelstra timestamping]: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-June/020569.html
```

2022-06-21 15:34 UTC, Xekyo reviewed
Thanks that was a great read

2022-06-21 15:34 UTC, Xekyo commented on _posts/en/newsletters/2022-06-22-newsletter.md
> +discussion about time stamping system design, and examines an new
```suggestion
discussion about time stamping system design, and examines a new
```

2022-06-21 15:34 UTC, Xekyo commented on _posts/en/newsletters/2022-06-22-newsletter.md
> +  resistant to attacks.
Would I understand correctly that address reuse exacerbates this? Perhaps we could call that out specifically to add to the well-known reasons for why address reuse is a bad practice.

2022-06-21 15:34 UTC, Xekyo commented on _posts/en/newsletters/2022-06-22-newsletter.md
> +  the listed UTXO owners created it.
Too many witches spoil the potion—that last sentence is a bit hard to parse. Perhaps:

```suggestion
  belongs to the user and the rest belong to other users.  The user then
  creates a signature which provably came from an owner
  of one of the listed UTXOs, but does not reveal which owner created it.
  ```

2022-06-21 15:34 UTC, Xekyo commented on _posts/en/newsletters/2022-06-22-newsletter.md
> +  potentially reduce the users privacy.  He writes, "there is no
```suggestion
  potentially reduce the user's privacy.  He writes, "there is no
```

2022-06-22 04:41 UTC, harding commented
Made edits (thanks @johnzweng and @Xekyo ), added releases, added topic links (just one this week), and reviewed @bitschmidty 's contribution (thanks!).  Thanks everyone!

2022-06-22 11:45 UTC, merged

2022-06-22 11:45 UTC, bitschmidty commented
Merged! Thanks @harding @Xekyo @johnzweng for contributing!