Create 2022-10-26-newsletter.md
bitcoinops/bitcoinops.github.io pull request #907
Opened 2022-10-26 16:58 UTC by Copinmalin

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +        opte pour le [RBF][topic rbf] soit disponible, mais estime que
Kotliar note que le problème existe déjà aujourd'hui avec la disponibilité de l'RBF][topic rbf] du [BIP125][], mais il estime que

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +        Greg Sanders and Jeremy Rubin [ont répondu][sanders cpfp]
Greg Sanders and Jeremy Rubin [notent][sanders cpfp]

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +        [separement][rubin cpfp] pour noter que le commerçant Bob
[séparement][rubin cpfp] que le commerçant Bob

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +      recommandation (en choisissant le défaut), mais fournir des options
recommandation (en choisissant l'option par défaut), mais fournir des options

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +  (TabConf), environ 40 développeurs ont participé à un événement
(TabConf), 40 développeurs environ ont participé à un événement

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +    - [Stratum v2][stratum v2 chat]: une discussion qui a commencée avec l'annonce
- [Stratum v2][stratum v2 chat]: une discussion qui a commencé avec l'annonce

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +    exploiter (plutôt que le pool qui choisit les transactions).  En plus de nombreux
exploiter (plutôt que le pool qui choisit les transactions). En plus de nombreux

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +    suggestions s'appliquent également à d'autres projets.  Idées incluses :
suggestions s'appliquent également à d'autres projets. Idées incluses :

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +  transaction number".
[Pourquoi une transaction aurait-elle un locktime en 1987 ? ]({{bse}}115549)
1440000bytes pointe vers un commentaire de Christian Decker faisant référence à [une section][bolt 3 commitment] de la spécification Lightning BOLT 3 qui attribue le champ locktime comme "les 8 bits supérieurs sont 0x20, les 24 bits inférieurs sont les 24 bits inférieurs du numéro de transaction d'engagement masqué".

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +  sur le réseau.  Un [guide de test] [bcc testing] est disponible.
sur le réseau. Un [guide de test] [bcc testing] est disponible.

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +La newsletter de cette semaine résume la suite de discussion sur l'activation
La newsletter de cette semaine résume la suite de discussions sur l'activation

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +      américaine gratuite. Par exemple, le client Alice demande à acheter
de style Option Américaine gratuite. Par exemple, le client Alice demande à acheter

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +        Greg Sanders était [incertain][sanders doubt], "la question est:
Greg Sanders était [circonspect][sanders doubt], "la question est :

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +        Towns [a répondu][towns uasf], "[UASF][topic soft fork activation]
Ce à quoi Towns [a répondu][towns uasf] : "[UASF][topic soft fork activation]

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +    - [Chiffrement du transport][p2p encryption]: une conversation sur
- [le chiffrement du transport][p2p encryption]: une conversation sur

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +    - [Frais][fee chat]: une large discussion sur les frais de transaction
- [les frais][fee chat]: une large discussion sur les frais de transaction

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +  Les principales discussions incluaient :
Les principales discussions portaient sur :

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +    - [Spécifications prévisibles dans les BIP][hacspec chat]: dans le cadre
- [les spécifications prévisibles dans les BIP][hacspec chat]: dans le cadre

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +    - [Paquet et relais de transactions v3][package relay chat]: la
- [les relais de transactions en paquet v3][package relay chat]: la

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +        - Divisez les grands changements en plusieurs petites PR
- Diviser les grands changements en plusieurs petites PR

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +    Jeremy Rubin [a répondu][rubin ephemeral] a soutenu la proposition mais a noté
Jeremy Rubin [a soutenu][rubin ephemeral] la proposition mais a noté

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +    tous semblant le trouver attrayant au moment de la rédaction de cet article.
tous semblent le trouver attrayant au moment de la rédaction de cet article.

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +avons quelques instants pour aider les utilisateurs curieux ou confus. Dans cette
avons quelques instants pour aider les utilisateurs curieux ou perdus. Dans cette

2022-10-30 11:50 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +  de la période de maturation de coinbase, ainsi que la nécessité de renégocier en permanence
de la période de maturation d'une coinbase, ainsi que la nécessité de renégocier en permanence

2022-10-30 12:19 UTC, Copinmalin commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +La newsletter de cette semaine résume la suite de discussion sur l'activation
Merci du retour

2022-10-30 14:11 UTC, Copinmalin commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +        Greg Sanders était [incertain][sanders doubt], "la question est:
j'aime bien circonspect :-)

2022-10-30 14:15 UTC, Copinmalin commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +    - [Stratum v2][stratum v2 chat]: une discussion qui a commencée avec l'annonce
@Jluc-bitcoinfr  n'est-ce pas la discussion qui a été commencée ?

2022-10-30 14:19 UTC, Copinmalin commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +avons quelques instants pour aider les utilisateurs curieux ou confus. Dans cette
je préfère confus, s'ils sont perdus c'est qu'ils ne sont pas au bon endroit ou ce n'est pas à cet endroit qu'ils trouveront leur chemin.

2022-10-31 08:18 UTC, Copinmalin commented
@bitschmidty  : hello, newsletter ready for review

2022-10-31 13:57 UTC, bitschmidty requested changes
A couple link fixes that I need your help with @Copinmalin

2022-10-31 16:50 UTC, Copinmalin commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +  pour exiger que chaque entrée de financement opte pour [RBF] [sujet rbf] et soit
Thnaks, all it's done now

2022-11-02 13:15 UTC, bitschmidty requested changes

2022-11-02 13:15 UTC, bitschmidty commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +[news222 rbf]: /en/newsletters/2022/10/19/#transaction-replacement-option
```suggestion
[news222 rbf]: /fr/newsletters/2022/10/19/#option-de-remplacement-de-transaction
```

2022-11-02 13:15 UTC, bitschmidty commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +[news222 bip324]: /en/newsletters/2022/10/19/#bip324-update
```suggestion
[news222 bip324]: /fr/newsletters/2022/10/19/#mise-a-jour-bip324
```

2022-11-02 13:15 UTC, bitschmidty commented on _posts/fr/newsletters/2022-10-26-newsletter.md
> +[news220 ephemeral]: /en/newsletters/2022/10/05/#ephemeral-dust
```suggestion
[news220 ephemeral]: /fr/newsletters/2022/10/05/#ephemeral-dust
```

2022-11-03 16:50 UTC, bitschmidty approved these changes
ACK, thanks for the translation @Copinmalin

2022-11-03 16:51 UTC, merged