Newsletter-229-translate-in-french
bitcoinops/bitcoinops.github.io pull request #957
Opened 2022-12-12 18:15 UTC by Copinmalin

2022-12-15 22:00 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +  a3="Il se peut que certains des ancêtres aient déjà été payés par certains de leurs
a3="Il se peut que certains des ascendants aient déjà été payés par certains de leurs

2022-12-15 22:00 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +      autres descendants; il n'est pas nécessaire d'en rajouter. Nous devons donc
autres descendants ; il n'est pas nécessaire d'en rajouter. Nous devons donc

2022-12-15 22:00 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +  a4="Oui. Si certains des ancêtres à faible taux de frais de Y ont _d'autres_ descendants
a4="Oui. Si certains des ascendants à faible taux de frais de Y ont _d'autres_ descendants

2022-12-15 22:01 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +      qui ont un taux de frais élevé, Y n'a pas besoin de "payer" pour ces ancêtres.
qui ont un taux de frais élevé, Y n'a pas besoin de "payer" pour ces ascendants.

2022-12-15 22:02 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +      L'ensemble des ancêtres de Y est mis à jour pour exclure ces transactions, ce qui a
L'ensemble des ascendants de Y est mis à jour pour exclure ces transactions, ce qui a

2022-12-15 22:13 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +      pour effet d'augmenter le taux de frais des ancêtres de Y."
pour effet d'augmenter le taux de frais des ascendants de Y."

2022-12-15 22:13 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +  a5="Elle sera surestimée si deux sorties dont l'ascendance se chevauche sont choisies,
Ce sera surestimé si deux sorties dont l'ascendance se chevauche sont choisies

2022-12-15 22:14 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +      puisque chaque saut est indépendant de ses ancêtres (sans tenir compte de l'ascendance
puisque chaque saut est indépendant de ses ascendants (sans tenir compte de l'ascendance

2022-12-15 22:19 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +      une transaction existante dans le pool de mémoires, (3) non confirmé (dans le pool
une transaction existante dans la mempool, (3) non confirmé

2022-12-15 22:20 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +      de mémoires) et non dépensé, (4) non confirmé mais déjà dépensé par une transaction
(dans la mempool) et non dépensé, (4) non confirmé mais déjà dépensé par une transaction

2022-12-15 22:21 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +      existante dans le pool de mémoires, ou (5) il pourrait être un point de sortie dont
existante dans la mempool, ou (5) il pourrait être un point de sortie dont

2022-12-15 22:21 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +      pour calculer les frais de saut (les frais nécessaires pour faire passer leurs ancêtres
pour calculer les frais de saut (les frais nécessaires pour faire passer leurs ascendants

2022-12-15 22:24 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +- [Core Lightning 22.11][] est la prochaine version majeure de CLN.  C'est également la
- [Core Lightning 22.11][] est la prochaine version majeure de CLN. C'est également la

2022-12-15 22:25 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +- [LND 0.15.5-beta][] st une version de maintenance de LND.  Elle ne contient que des
- [LND 0.15.5-beta][] est une version de maintenance de LND.  Elle ne contient que des

2022-12-15 22:29 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +    Cependant, le protocole LN requiert certains types de sortie.  Par exemple
Cependant, le protocole LN requiert certains types de sortie. Par exemple

2022-12-15 22:29 UTC, Jluc-bitcoinfr commented on _posts/fr/newsletters/2022-12-07-newsletter.md
> +    nouvelles versions continueraient à utiliser ce schéma à l'avenir.  Rusty
nouvelles versions continueraient à utiliser ce schéma à l'avenir. Rusty

2022-12-16 16:15 UTC, bitschmidty requested changes
@Copinmalin can you correct the build errors?

Appears currently:

> _posts/fr/newsletters/2022-12-07-newsletter.md:191: MD009 Trailing spaces

2022-12-17 16:25 UTC, bitschmidty reviewed
@Copinmalin Travis CI is showing an error in the PR review section of the translation. When Ive seen this in the past it has been mis-matched quotes " but could be something else. Maybe try taking out questions one by one until it works to help see where the error is

2022-12-17 17:58 UTC, Copinmalin commented
sorry @bitschmidty I don't understand what's wrong with Q/A parts
I change every ", nothing change
:,-(

2022-12-17 18:34 UTC, Copinmalin commented
YEEEESSSS ! Check :-)

2022-12-19 18:32 UTC, bitschmidty approved these changes
ACK, thank you @Copinmalin !

2022-12-19 18:32 UTC, merged